### ISSUE TITLE
Rescue mode not working from Cleura Cloud Management Panel (CCMP)

### ISSUE THREAD

**Issue by Tomas-Rinblad-at-cleura** [citynetwork/docs#173]
### Summary

When trying to perform a rescue mode on a boot from volume server via CCMP it always returns back to Active state instead of going into rescue mode. If I run the CLI part of the documentation that works as expected.
When performing the same test on a server using Ephemeral disk it works fine.

### URL path

https://docs.cleura.cloud/howto/openstack/nova/rescue-server/

### What I did

Created a bfv server and followed the CCMP guide.

### What I expected to observe

The server to go into rescue mode.

### What I actually observed

The server only went back to Active state instead.

### My environment

I am using Brave and Safari as Browser.
I have the issue with both Ubuntu and CentOS

**Comment by fghaas** [comment]
Closing: this isn't a documentation bug; it was a bug in CCMP functionality that has been fixed.
