### ISSUE TITLE
On force push, reviews are not discarded

### ISSUE THREAD

**Issue by evrardjp** [citynetwork/docs#3]
IMO, pushes to a PR's branch should automatically discard votes on that PR. 
WDYT?

**Comment by fghaas** [comment]
To the best of my knowledge GitHub lets you configure that only on protected branches. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by evrardjp** [comment]
Yes, of course... I should start by asking should we protect our main branch? It makes sense to me.
